<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */
?>
<div class="admin__table-wrapper">
    <table class="data-table admin__table-primary order-shipment-table">
        <?php $shipment = $block->getShipment() ?>
        <?php $_items = $shipment->getAllItems() ?>
        <?php $shipmentItemIds = []; ?>
        <?php foreach($_items as $_item) { $shipmentItemIds[] = $_item->getEntityId(); } ?>
        <?php $_detail_items = $block->getChildBlock('ppm_shipment_detail')->getPpmShipmentDetails($shipmentItemIds) ?>

        <?php if($shipment->getFulfilledByPpm()): ?>
            <thead>
                <tr class="headings">
                    <th class="col-product"><span><?= $block->escapeHtml(__('Product')) ?></span></th>
                    <th class="col-qty last"><span><?= $block->escapeHtml(__('SKU')) ?></span></th>
                    <th class="col-qty last"><span><?= $block->escapeHtml(__('PPM SKU')) ?></span></th>
                    <th class="col-qty last"><span><?= $block->escapeHtml(__('Qty Shipped')) ?></span></th>
                    <th class="col-qty last"><span><?= $block->escapeHtml(__('Lot Number')) ?></span></th>
                    <th class="col-qty last"><span><?= $block->escapeHtml(__('Serial Number')) ?></span></th>
                </tr>
            </thead>
            <?php foreach ($_items as $_item) :
                if (!empty($_item->getOrderItem())) :
                    if ($_item->getOrderItem()->getParentItem()) :
                        continue;
                    endif;
                    ?>
                    <?php $_i = 0; foreach ($_detail_items as $_detail_item): $_i++ ?>
                        <?php if ($_detail_item->getSalesShipmentItemId() == $_item->getEntityId()) : ?>
                            <tbody class="<?= /* @noEscape */ $_i%2 ? 'odd' : 'even' ?>">
                            <tr class="border">
                                <td><?= $_item->getName() ?></td>
                                <td><?= $_item->getOrderItem()->getProduct()->getSku() ?></td>
                                <td><?= $_detail_item->getPpmMerchantSku() ?></td>
                                <td><?= $_detail_item->getQuantity() ?></td>
                                <td><?= $_detail_item->getLotNumber() ?></td>
                                <td><?= $_detail_item->getSerialNumber() ?></td>
                            </tr>
                            </tbody>
                        <?php endif; ?>
                    <?php endforeach; ?>
                 <?php endif; ?>
            <?php endforeach; ?>
        <?php else: ?>
            <thead>
                <tr class="headings">
                    <th class="col-product"><span><?= $block->escapeHtml(__('Product')) ?></span></th>
                    <th class="col-qty last"><span><?= $block->escapeHtml(__('Qty Shipped')) ?></span></th>
                </tr>
            </thead>
            <?php $_i = 0; foreach ($_items as $_item) :
                if (!empty($_item->getOrderItem())) :
                    if ($_item->getOrderItem()->getParentItem()) :
                        continue;
                    endif;
                    $_i++ ?>
                    <tbody class="<?= /* @noEscape */ $_i%2 ? 'odd' : 'even' ?>">
                        <?= $block->getItemHtml($_item) ?>
                        <?= $block->getItemExtraInfoHtml($_item->getOrderItem()) ?>
                    </tbody>
                <?php endif; ?>
            <?php endforeach; ?>
        <?php endif; ?>
    </table>
</div>
